#!/bin/zsh

git_branch() {
    # 현재 Git 디렉토리가 아닐 경우 오류 메시지 출력
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        echo "(not a git repository)"
        return
    fi

    # 현재 브랜치 이름을 변수에 저장
    branch=$(git symbolic-ref --short HEAD 2>/dev/null)

    # 브랜치가 없을 경우 (예: detached HEAD 상태) 메시지 출력
    if [ -z "$branch" ]; then
        branch="(detached HEAD)"
    fi

    # 변경사항이 있는지 확인
    if [ -n "$(git status --porcelain)" ]; then
        echo " ($branch*)"
    else
        echo " ($branch)"
    fi
}

function lscolor
{
    for color in {0..255}; do
        print -P "%F{$color} $color %f"
    done
}

my_zsh_prompt()
{
    GIT=$(git_branch)

    unset PS1
	if [ "$TERM" = "xterm-256color" ]; then
        TIME="[%F{%(#.blue.50)}%D{%a %m-%d %H:%M:%S}%f]"
        CWD="%F{yellow}[dir]: %~%f"
        GIT="%F{green}"$GIT"%f "
        USER_NAME='%F{%(#.red.39)}%n%f'
        HOST_NAME=$HOST
        STATUS='%F{39}%f %? %(#.%(?.#.%F{red}#%f).%(?.%%.%F{red}%%%f)) '
        LINE=$'\n''%U'${(r:COLUMNS:: :)}'%u'$'\n'
        PS1=$LINE$TIME$GIT$CWD$'\n'$USER_NAME'@'$HOST_NAME$STATUS 
	else
	    TIME="\n[\d \t]"
        CWD="[job]: \j [dir]: \w"
        HOST="\u@\h"
        exit_status="\$?"
        PS1=$'%U${(r:$COLUMNS:: :)}%u'"${TIME} ${GIT} ${CWD} \n${HOST} $exit_status $ "
	fi
}

my_zsh_prompt
