#!/bin/bash
# Console Style Constants
RST="\[\e[0m\]"           # Reset Styles
BOLD="\[\e[1m\]"          # Bold
UL="\[\e[4m\]"            # Underline
HIGHLIGHT="\[\e[7m\]"     # Highlight (inverse)
FG_BLACK="\[\e[90m\]"     # Foreground black
FG_RED="\[\e[91m\]"       # Foreground red
FG_GREEN="\[\e[92m\]"     # Foreground green
FG_YELLOW="\[\e[93m\]"    # Foreground yellow
FG_BLUE="\[\e[94m\]"      # Foreground blue
FG_MAGENTA="\[\e[95m\]"   # Foreground magenta
FG_CYAN="\[\e[96m\]"      # Foreground cyan
FG_WHITE="\[\e[97m\]"     # Foreground white
BG_BLACK="\[\e[100m\]"    # Background black
BG_RED="\[\e[101m\]"      # Background red
BG_GREEN="\[\e[102m\]"    # Background green
BG_YELLOW="\[\e[103m\]"   # Background yellow
BG_BLUE="\[\e[104m\]"     # Background blue
BG_MAGENTA="\[\e[105m\]"  # Background magenta
BG_CYAN="\[\e[106m\]"     # Background cyan
BG_WHITE="\[\e[107m\]"    # Background white

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export GPG_TTY=$(tty)
unset SSH_AGENT_PID
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QR_IM_MODULE=ibus

export GIT_CURL_VERBOSE=1 
export GIT_TRACE=1

export LANG=ko_KR.UTF-8
export LESSCHARSET=utf-8

[[ -f ~/.config/emacs/bin ]]  && export PATH=$HOME/.config/emacs/bin:$PATH

export GIT_PS1_SHOWUPSTREAM="verbose name"
export GIT_PS1_DESCRIBE_STYLE="branch"
export GIT_PS1_SHOWCOLORHINTS="true"

draw_line()
{
  local COLUMNS="$COLUMNS"
  while ((COLUMNS-- > 0)); do
    printf '\u2500'
  done
}

my_bash_prompt()
{
	# set a fancy prompt (non-color, unless we know we "want" color)
	case "$TERM" in
	    xterm-color|*-256color) color_prompt=yes;;
	esac

	if [ "$TERM" = "xterm-256color" ]; then
	    TIME="\n${FG_BLUE}[\d \t]${RST}"
	    CWD="${FG_YELLOW}[job]: \j [dir]: \w${RST}${debian_chroot:+($debian_chroot)}"
	    HOST="${FG_GREEN}${BOLD}\u${RST}${FG_WHITE}@${RST}${FG_CYAN}\h${RST}"
	    GIT="`__git_ps1`"
	    exit_status="\$?"
	    PS1='$(draw_line)'"${TIME} ${GIT} ${CWD} \n${HOST} $exit_status $ "        
	else
	    PS1='\n[\d \t]\u@\h:\w\ `__git_ps1` ${STATUS} '
	fi
}

my_bash_prompt
